# このファイルのバージョン（ZMKでは現行バージョン "1" が一般的）
file_format: "1"

# このシールドの識別ID（ビルドや設定で使用）
id: sparkle

# シールドの表示名（GUIやエディタで使われる）
name: SPARKLE

# シールドの種類を指定（ここでは `shield` → ハードウェア構成の定義）
type: shield

# このシールドに関するURL（Gitリポジトリやドキュメントへのリンク）
url: https://github.com/Hinata-344/my-shield-module-test/tree/byHutabaForMe

# このシールドのビルドや実行に必要なボード名（Seeeduino XIAO BLEを前提としている）
requires: [seeeduino_xiao_ble]

# このシールドが提供する機能。`keys` は物理キースイッチが含まれていることを示す
features:
  - keys

# このシールドが内包する兄弟（左右分割構成などで用いる）
siblings:
  - sparkle_left
  - sparkle_right
